spring:
  application:
    name: yoajung-admin

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
#      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true

  cloud:
    aws:
      credentials:
        accessKey: "${S3_ACCESSKEY}"
        secretKey: "${S3_SECRETKEY}"
      region:
        static: ap-northeast-2
      s3:
        bucket: yoajung-img
      stack:
        auto: false

  ai:
    openai:
      api-key: "${OPENAI_API_KEY}"
      chat:
        options:
          model: gpt-4o
          temperature: 0.5
    chat:
      system-prompt1: classpath:prompt/agePrompt.txt
      system-prompt2: classpath:prompt/chatPrompt.txt

logging:
  level:
    org.hibernate.SQL: debug             # 실행되는 SQL 로그
    org.hibernate.type.descriptor.sql: trace   # 바인딩된 파라미터 값도 출력됨

dify:
  base-url: https://api.dify.ai/v1
  api-key : ${DIFY_KEY}